// flow-typed signature: 2e66d5e6e968a8a041035f2ce460c786
// flow-typed version: <<STUB>>/base64-arraybuffer_v0.1.5/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-arraybuffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-arraybuffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base64-arraybuffer/lib/base64-arraybuffer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base64-arraybuffer/lib/base64-arraybuffer.js' {
  declare module.exports: $Exports<'base64-arraybuffer/lib/base64-arraybuffer'>;
}
